KadekeTripBundle_default:
    resource: "@KadekeTripBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
KadekeTripBundle_trippage_admin_list:
    resource: @KadekeTripBundle/Controller/Trip/TripPageAdminListController.php
    type:     annotation
    prefix:   /admin/trippage/
    requirements:
         _locale: %requiredlocales%
