parameters:
#    kadeke_trip.example.class: Kadeke\TripBundle\Example

services:
#    kadeke_trip.example:
#        class: %kadeke_trip.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
