KadekeTravelBundle_travelpage_admin_list:
    resource: @KadekeTravelBundle/Controller/Travel/TravelPageAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/travelpage/
    requirements:
         _locale: %requiredlocales%

KadekeTravelBundle_travelauthor_admin_list:
    resource: @KadekeTravelBundle/Controller/Travel/TravelAuthorAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/travelauthor/
    requirements:
         _locale: %requiredlocales%

KadekeTravelBundle_travel:
    resource: @KadekeTravelBundle/Controller/TravelController.php
    type:     annotation
    prefix:   /
    requirements:
         _locale: %requiredlocales%