KadekeTravelBundle_default:
    resource: "@KadekeTravelBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

KadekeTravelBundle_travelpage_admin_list:
    resource: @KadekeTravelBundle/Controller/Travel/TravelPageAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/travelpage/
    requirements:
         _locale: %requiredlocales%

KadekeTravelBundle_travelauthor_admin_list:
    resource: @KadekeTravelBundle/Controller/Travel/TravelAuthorAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/travelauthor/
    requirements:
         _locale: %requiredlocales%
