<?php

namespace Kadeke\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCommentRepository extends EntityRepository
{
}
