<?php

namespace Kadeke\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCommentRepository extends EntityRepository
{

    /**
     * Returns a list of BlogComments with parent $blogentry
     * Ordered by ascending timestamp
     *
     * @param $id int
     *
     * @return array
     */
    public function findByBlogEntry($id)
    {
        return array();
        //return $this->findBy(array('parent' => $id), array('timestamp' => "ASC"));
    }

}
