KadekeBlogBundle_blogauthor_admin_list:
    resource: @KadekeBlogBundle/Controller/BlogAuthorAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/blogauthor/
    requirements:
         _locale: %requiredlocales%
