KadekeBlogBundle_blogauthor_admin_list:
    resource: @KadekeBlogBundle/Controller/BlogAuthorAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/blogauthor/
    requirements:
         _locale: %requiredlocales%

KadekeBlogBundle_blogcomment_admin_list:
    resource: @KadekeBlogBundle/Controller/BlogCommentAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/blogcomment/
    requirements:
         _locale: %requiredlocales%

KadekeBlogBundle_blogentry:
    resource: @KadekeBlogBundle/Controller/BlogEntryController.php
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%

KadekeBlogBundle_blogcomment:
    resource: @KadekeBlogBundle/Controller/BlogCommentController.php
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%