parameters:
#    kadeke_blog.example.class: Kadeke\BlogBundle\Example

services:
    kadeke_blog.menu.adaptor:
        class: Kadeke\BlogBundle\Helper\Menu\BlogMenuAdaptor
        tags:
            - { name: kunstmaan_admin.menu.adaptor }
