parameters:
#    kadeke_blog.example.class: Kadeke\BlogBundle\Example

services:
#    kadeke_blog.example:
#        class: %kadeke_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
