parameters:
#    kadeke_website.example.class: kadeke\WebsiteBundle\Example

services:
#    kadeke_website.example:
#        class: %kadeke_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
