parameters:
#    kadeke_website.example.class: Kadeke\WebsiteBundle\Example

services:
    kadeke_website.language_listener:
        class: Kadeke\WebsiteBundle\EventListener\LanguageListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

